### ISSUE TITLE
Code Coverage report?

### ISSUE THREAD

**Issue by villasv** [XpiritBV/Xpirit-Vsts-Build-Pester#3]
It would be nice if the extension also generated code coverage reports.

I think it's not much work to make it happen, you would only need to also get the desired source files in order to issue another Pester command.

**Comment by pgroene** [comment]
Yes, I have looked into this. However the format from Pester is not directly usable by VSTS. There has to be a conversion, which is a little more work in time than I have at this moment. Add to nice to have list...
