### ISSUE TITLE
Update to allow tag filtering ?

### ISSUE THREAD

**Issue by kevinbowman** [XpiritBV/Xpirit-Vsts-Build-Pester#4]
Any chance this could be updated to allow tag filtering in the task please?

**Comment by pgroene** [comment]
Never used tag filtering with pester, do you have any good samples? I guess you want to run a subset of your tests. 
A PR would be wonderful.

**Comment by kevinbowman** [comment]
Yes to run a subset of tests.

@pgroene I've raised a PR with a tested solution.  Please take a look.  Thanks.

**Comment by pgroene** [comment]
Thx for the PR, I'll test it asap.
