### ISSUE TITLE
Support parameters being passed

### ISSUE THREAD

**Issue by kevinbowman** [XpiritBV/Xpirit-Vsts-Build-Pester#5]
Currently I use this VSTS Task, it's great.  We write pester test to pull VSTS environment variables, but this is making our pipelines somewhat brittle, as the code is couples to the pipeline variable naming.

Can you add a option to pass in parameters to the test scripts please?

**Comment by pgroene** [comment]
Can you give some code samples on how you are doing this, so I can make a good guess on what has to be done and if it is feasible.

**Comment by kevinbowman** [comment]
@pgroene I've raised a PR with a tested solution.  Please take a look.  Thanks

**Comment by pgroene** [comment]
Thx for the pr, I'll look at is asap.
