### ISSUE TITLE
Recursive itemSpec not working

### ISSUE THREAD

**Issue by drewkg** [XpiritBV/Xpirit-Vsts-Build-Pester#9]
Have tried the search path *.tests.ps1 and **.tests.ps1 and '**\*.tests.ps1' and the recursive folder search fails to find my tests.

If I specify a directory specifically then *.tests.ps1 finds all files in the directoy.

**Comment by pgroene** [comment]
Thank you for taking the time to ask this. I think you need to use ** in stead of * for directories:

**/*.tests.ps1
